# Generated by Django 3.0.8 on 2020-08-23 17:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200809_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('subtitle', wagtail.core.blocks.CharBlock(classname='full title')), ('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('more_information', wagtail.core.blocks.PageChooserBlock(help_text='Select a page where a member can find more information', required=False))]))]),
        ),
    ]
