# Generated by Django 3.0.8 on 2020-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_eventpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, help_text='Optional; add a title or heading for this specific event.', max_length=100, null=True)),
                ('date', models.DateField(help_text='Enter the date and time of the event.')),
            ],
        ),
    ]
