# Generated by Django 3.0.8 on 2020-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='heading',
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, help_text='Optional; add a title for this specific event.', max_length=100, null=True),
        ),
    ]
