# Generated by Django 3.0.8 on 2020-12-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20201217_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='Enter the date and time of the event.'),
        ),
    ]
