# Generated by Django 3.0.8 on 2021-01-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210126_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_phone', to='members.Member'),
        ),
    ]
