# Generated by Django 3.0.8 on 2021-03-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210126_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_geographies', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_phones', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_subjects', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_taxons', to='members.Member'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_emails', to='members.Member')),
            ],
        ),
    ]
